controller_list:
  - name: fake_robot_arm_controller
    type: $(arg execution_type)
    joints:
      - rotate_base
      - joint1
      - joint2
      - joint3
  - name: fake_hand_controller
    type: $(arg execution_type)
    joints:
      - left_gripper
      - right_gripper
initial:  # Define initial robot poses.
  - group: robot_arm
    pose: default