# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: robot_arm
  joint_model_group_pose: default
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - rotate_base
    - joint1
    - joint2
    - joint3
    - left_gripper
    - right_gripper
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []
joint_control:
  type: position_controllers/JointPositionController
  joints:
    - rotate_base
    - joint1
    - joint2
    - joint3
    - joint4
  gains:
    rotate_base:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1

